name: simple_managers
description: A package containing multiple manager classes that support serialization.
version: 7.0.5
repository: https://github.com/MasahideMori-SimpleAppli/simple_managers

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  file_state_manager: ^3.0.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_lint: ^2.0.0
